### ISSUE TITLE
Tracking issue for pyiceberg changes to achieve compatibility

### ISSUE THREAD

**Issue by c-thiel** [lakekeeper/lakekeeper#18]
Currently there are a few issues with pyiceberg compatibility.
We should open issues for those:

* pyiceberg prepends `warehouse`-name to namespaces. This is against the Iceberg-Rest spec.
https://github.com/apache/iceberg-python/blob/20b7b5339a1a0ab59d884c7d042c4bc96a166b11/pyiceberg/catalog/rest.py#L464
* If `warehouse` name is None, the first segment of Namespaces is missing:
https://github.com/apache/iceberg-python/blob/20b7b5339a1a0ab59d884c7d042c4bc96a166b11/pyiceberg/catalog/rest.py#L356 (notice [1:] ...)
* FSSPEC does not honor "s3.signer.uri" property:
https://github.com/apache/iceberg-python/blob/20b7b5339a1a0ab59d884c7d042c4bc96a166b11/pyiceberg/io/fsspec.py#L75
* Only vended credentials are supported even though remote signing via fsspec is also possible

**Comment by c-thiel** [comment]
- [x] https://github.com/apache/iceberg-python/issues/742
- [x] https://github.com/apache/iceberg-python/issues/740
- [x] https://github.com/apache/iceberg-python/issues/735

**Comment by c-thiel** [comment]
Compatability will come with pyiceberg 0.7.0

**Comment by corleyma** [comment]
It looks like pyiceberg 0.7.0 release it about to be cut, but without apache/iceberg-python#742.

**Comment by c-thiel** [comment]
> It looks like pyiceberg 0.7.0 release it about to be cut, but without [apache/iceberg-python#742](https://github.com/apache/iceberg-python/issues/742).

Thanks for thinking about us. If we have to we can build around then on the catalog side as well. Glad that pyiceberg is running the extra round to harmonize across catalogs.

**Comment by c-thiel** [comment]
All pyiceberg-issues solved - thanks folks!
Last one on our side for remote signing: https://github.com/hansetag/iceberg-catalog/pull/212
